
modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved"
issueTrackerURL="https://github.com/MaxLegend/Soviet-Era-2/issues" #optional

[[mods]]
modId = "soviet" #mandatory
version = "Alpha-2.2"
# A display name for the mod
displayName = "Soviet Era 2" #mandatory
updateJSONURL="https://github.com/MaxLegend/Soviet-Era-2/blob/1.16.5-dev/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/soviet-era-mod" #optional
logoFile="logo.png"
credits="Thanks Max_Freemen, SlimeF, Vincent11A, Peresmechnic, lrx1tp, for 3d models and textures"
authors="Tesmio"

description = '''
A modification that will allow you to plunge into the atmosphere of the frightening dungeons of the Soviet era and get a lot of useful resources there.
'''
[[dependencies.soviet]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soviet]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
